import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
 import { Button } from "@/components/ui/button"
 import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuIndicator,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
  NavigationMenuViewport,
} from "@/components/ui/navigation-menu"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="bg-amber-500">
    <NavigationMenu className="bg-amber-500">
  <NavigationMenuList className="bg-amber-500">
    <NavigationMenuItem className="bg-amber-500">
      <NavigationMenuTrigger  className="mx-28 bg-amber-500">Home</NavigationMenuTrigger>
      <NavigationMenuTrigger className="mx-28 bg-amber-500">about</NavigationMenuTrigger>
      <NavigationMenuTrigger className="mx-28 bg-amber-500">Login</NavigationMenuTrigger>
      <NavigationMenuTrigger className="mx-28 bg-amber-500">Signup</NavigationMenuTrigger>
    </NavigationMenuItem >
  </NavigationMenuList >
</NavigationMenu>
    </div>
        {children}
      </body>
    </html>
  );
}
